encoding: utf-8
title: lets-code
description: lets learn to code
theme: jekyll-theme-hacker
author: mnciitbhu
authorsite: https://mnciitbhu.me/

relative_links:
  enabled:     true
  collections: false

#github:
  #repository_url: https://mnciitbhu.me/lets-code/github

#plugins:
  #- jekyll-redirect-from
